<?php

/**
 * OntoWiki linkinghere module template
 * TODO: use rev (with curie'd property) and resource instead of only about?
 *
 * @version $Id: linkinghere.phtml 3396 2009-06-26 15:01:44Z sebastian.dietzold $
 */
function buildFilterExp($res, $pred, $label){
    $allfilter = array(
        'filter' => array(
            array (
                'action' => 'add',
                'mode' => 'box',
                'id' => 'linkinghere',
                'property' => $pred,
                'isInverse' => false,
                'propertyLabel' => $label,
                'filter' => 'equals',
                'value1' => $res,
                'value2' => null,
                'valuetype' => 'uri',
                'literaltype' => null,
                'hidden' => false
            )
        )
    );
    return urlencode(json_encode($allfilter));
}
?>
<?php if (!empty($this->instances)): ?>
	<ul class="bullets-none separated">
	    <?php foreach ($this->instances as $property => $instances): ?>
        <?php $relation = $this->properties[$property] ?>
	        <li class="has-contextmenu-area">
                <strong>
					<?php echo $relation['title'] ?><sup>-1</sup>
               </strong>
	            <ul class="inline separated"  style="padding-left: 0.5em;">
	                <?php $i = 0; ?>
	                <?php foreach ($instances as $instance): ?>
	                    <?php if ((++$i == count($instances)) && ($relation['has_more'] == false)): ?>
	                        <li class="last-child"><a class="hasMenu" about="<?php echo $instance['uri'] ?>" href="<?php echo $instance['url'] ?>" onClick="Diaglog.logSearch('Navigate inverse relation', '<?php echo $instance['title'] ?>', '<?php echo $relation['title'] ?>', '', '<?php echo $instance['uri'] ?>', false);"><?php echo $instance['title'] ?></a></li>
	                    <?php else: ?>
	                        <li><a class="hasMenu" about="<?php echo $instance['uri'] ?>" href="<?php echo $instance['url'] ?>" onClick="Diaglog.logSearch('Navigate inverse relation', '<?php echo $instance['title'] ?>', '<?php echo $relation['title'] ?>', '', '<?php echo $instance['uri'] ?>', false);"><?php echo $instance['title'] ?></a></li>
	                    <?php endif; ?>
                        <?php endforeach; ?>
                    <?php if ($relation['has_more'] == true): ?>
                            <li>&hellip;</li>
                    <?php endif; ?>
	            </ul>
	            <form action="<?php echo $this->urlBase; ?>list/?init"
	            	  onsubmit="return Diaglog.logSearch('Inversely related instances list', '<?php echo $relation['title'] ?>', '<?php echo $relation['title'] ?>', '', '', false);"
	            	  method="get">
	            	  <input type="hidden" value="instancesconfig=<?php echo buildFilterExp((string)$this->resource, $property, $this->properties[$property]); ?>">
	                   <input type="submit" value="show as list">
	                  </form>
	             </li>
	    <?php endforeach; ?>
	</ul>
<?php else: ?>
	<p class="messagebox info"><?php echo $this->_($this->message) ?></p>
<?php endif; ?>
